### PR TITLE
hide the load more button if we already have anything

### PR DESCRIPTION
**Pull request by benharri**
sets a record limit and checks if the returned count has that limit

### CODE REVIEW

**Comment by tom-sherman** [comment]
What's the reason for wanting to stop scrolling back through more than 100 records?

**Comment by benharri** [comment]
This started as a way to hide the button if the entire collection was loaded. Happy to change the limit as it was previously using the default param for `listRecords` which was 50

**Comment by benharri** [comment]
the main point is that you don't see the load more button on collections that have less than FETCH_LIMIT items and have loaded completely like this https://atproto-browser-jpq042ggs-likeandscribe.vercel.app/at/did:plc:2xau7wbgdq4phuou2ypwuen7/app.bsky.actor.profile

**Review by tom-sherman — APPROVED** [review]
Looks good, apologies I misunderstood the purpose of this PR before!

**Pull request merged**
